package io.github.angbang852.manjiao.hook

import android.app.Activity
import android.os.Handler
import android.os.Looper
import io.github.libxposed.api.XposedInterface

// ★ ContentFilterHook 深拆第二步/状态收敛（2026-09 S3）：全量可变状态与运行时
// 基础设施（handler/执行器/缓存/计数器/引用/队列）收敛为单一单例。
// 判定 CfhDecide / 清洗 CfhClean / 捕获 CfhCapture / 诊断 CfhDiag 与主钩子文件
// 共享同一份状态——任何对象不得自行持有副本，避免多份状态漂移。
object CfhState {
    val handler = Handler(Looper.getMainLooper())
    @Volatile var tracked: Activity? = null
    var lastSkipTime = 0L
    @Volatile var xpRef: XposedInterface? = null
    @Volatile var clRef: ClassLoader? = null
    @Volatile var vmRef: Any? = null
    @Volatile var adpRef: Any? = null
    val adpRefs = java.util.Collections.synchronizedList(mutableListOf<Any>())
    var elemDumped = false
    @Volatile var qpClassRef: Class<*>? = null
    val hookedDsClasses = mutableSetOf<String>()
    @Volatile var liveTop = false
    var krnProbeHooked = false
    var krnProbeRetries = 0
    var krnProbeCount = 0
    var krnRcvHooked = false
    var krnRcvRetries = 0
    var krnLmDiag = 0
    val hookedRerankCls = java.util.Collections.newSetFromMap(java.util.concurrent.ConcurrentHashMap<String, Boolean>())
    var rerankJDiag = 0
    var rerankScrollDiag = 0
    var rerankListDiag = 0
    var rerankSingleDiag = 0
    var plistSkipDiag = 0
    var lastAdpSelfFix = 0L
    val hookedPageLists = mutableSetOf<String>()
    var knhbT0Hooked = false
    var knhbT0Diag = 0
    var knhbCallDiag = 0
    @Volatile var bootFlushDone = false
    @Volatile var bootFlushPending = false
    var knhbInst: java.lang.ref.WeakReference<Any>? = null
    val seenPhotoIds = LinkedHashSet<String>()
    val photoIdCache = java.util.Collections.synchronizedMap(java.util.IdentityHashMap<Any, String?>())
    val pidMCache = java.util.concurrent.ConcurrentHashMap<Class<*>, java.lang.reflect.Method>()
    val pidMNeg = java.util.Collections.newSetFromMap(java.util.concurrent.ConcurrentHashMap<Class<*>, Boolean>())
    var dedupeDiag = 0
    var dedupeProbe = 0
    val dedupeStarve = java.util.concurrent.atomic.AtomicInteger(0)
    val hookedMilanoContainers = mutableSetOf<String>()
    var liveCtorDiag = 0
    val liveCtorHookedCls = java.util.Collections.newSetFromMap(java.util.concurrent.ConcurrentHashMap<String, Boolean>())
    @Volatile var laRef: Any? = null
    @Volatile var laWatchArmed = false
    val laLogN = java.util.concurrent.atomic.AtomicInteger(0)
    val retDelQp = java.util.Collections.synchronizedList(ArrayList<Any?>())
    @Volatile var laFindAt = 0L
    val laFindPending = java.util.concurrent.atomic.AtomicBoolean(false)
    var truesrcCapDiag = 0
    val trueListRefs = java.util.concurrent.CopyOnWriteArrayList<Any>()
    val trueWatchIds = java.util.concurrent.CopyOnWriteArrayList<Int>()
    val hookedTrueCls = java.util.Collections.newSetFromMap(java.util.concurrent.ConcurrentHashMap<String, Boolean>())
    val trueListLogN = java.util.concurrent.atomic.AtomicInteger(0)
    var lastPagerSearch = 0L
    @Volatile var lastViewQp: Any? = null
    var aiFullDumpCount = 0
    @Volatile var visiblePhotoRef: java.lang.ref.WeakReference<Any>? = null
    val posPhotoMap = java.util.LinkedHashMap<Int, java.lang.ref.WeakReference<Any>>()
    val liveSlideFragments =
    java.util.Collections.newSetFromMap(java.util.Collections.synchronizedMap(java.util.WeakHashMap<Any, Boolean>()))
    @Volatile var lastVisibleFragRef: java.lang.ref.WeakReference<Any>? = null
    @Volatile var lastCaptureTrusted = false
    val visRing = java.util.ArrayDeque<CfhCapture.VisEntry>()
    @Volatile var realFragClass: Class<*>? = null
    val fragSeqHookedClasses = mutableSetOf<String>()
    val fragSeqCount = java.util.concurrent.atomic.AtomicInteger(0)
    var vpBlockDiag = 0
    var gqDumpCount = 0
    val fragSetterHooked = mutableSetOf<String>()
    @Volatile var inFindClean = false
    var lastClean: Any? = null
    var vmReplacedDiag = 0
    var offerDiag = 0
    var findCleanDiag = 0
    var vmRetNameDiag = 0
    var vmKeepDiag = 0
    val cleanQueue = ArrayDeque<Any>()
    val cleanCachePersist = ArrayDeque<Any>()
    val dirtyUrls = java.util.concurrent.ConcurrentHashMap.newKeySet<String>()
    val cleanUrlPool = ArrayDeque<String>()
    val hookedVmUrlClasses = mutableSetOf<String>()
    var urlSubCount = 0
    var playerHookTried = false
    @Volatile var dataDiag = 0
    var capturedLines = 0
    var liveDumpCount = 0
    var dramaDumpCount = 0
    val liveDumped = java.util.Collections.newSetFromMap(java.util.concurrent.ConcurrentHashMap<Int, Boolean>())
    val dramaDumped = java.util.Collections.newSetFromMap(java.util.concurrent.ConcurrentHashMap<Int, Boolean>())
    val capturedIds = java.util.Collections.newSetFromMap(java.util.concurrent.ConcurrentHashMap<Int, Boolean>())
    var pagerCache: Any? = null
    var holderDumpCount = 0
    var vmGetSubCount = 0
    var vmMethodDump = 0
    var fragDiagCount = 0
    var fragMethodsDiag = false
    var fragFieldsDiag = false
    val hookedAdpClasses = mutableSetOf<String>()
    var feedPagerFound = false
    var feedPagerLogCount = 0
    var adpDumpCount = 0
    val hookedPagerCls = java.util.Collections.newSetFromMap(java.util.concurrent.ConcurrentHashMap<String, Boolean>())
    var liveWindowDiag = 0
    var pagerDiag = 0
    var pagerSwapCount = 0
    val hookedProvClasses = mutableSetOf<String>()
    var provDiag = false
    var adpGetDiag = 0
    var adpGetLiveSkipDiag = 0
    var adpProvDiag = 0
    var adpQpDiag = 0
    var adpXDump = 0
    var adpXLiveZapDiag = 0
    // adpXRedirectDiag 已随「脏页位置重定向」死代码一并移除（2026-09-21）：从未生效
    val adpXDumped = java.util.Collections.newSetFromMap(java.util.concurrent.ConcurrentHashMap<String, Boolean>())
    var adpSelfDumped = false
    var adpGetSwapIn = false
    val methodCache = java.util.concurrent.ConcurrentHashMap<String, java.lang.reflect.Method>()
    val dirtyEntSeen = java.util.concurrent.ConcurrentHashMap.newKeySet<String>()
    val hookedVmClasses = mutableSetOf<String>()
    @Volatile var lretDiagCount = 0
    var vmYDiag = 0
    var vmListDiagDone = false
    var vmListElDump = 0
    var vmAllFieldsDumped = false
    @Volatile var lastViewSig = ""
    @Volatile var lastFilterVmListsAt = 0L
    @Volatile var vmRefProbeDone = false
    val cleanExecutor = java.util.concurrent.Executors.newSingleThreadExecutor { r ->
    Thread(r, "ManJiaoClean").apply { isDaemon = true }
}
    val pendingCleanObj = java.util.concurrent.atomic.AtomicReference<Any?>()
    val cleanDrainArmed = java.util.concurrent.atomic.AtomicBoolean(false)
    var filterResultDiag = 0
    var fltCallerDiag = 0
    val retThrottle = java.util.concurrent.ConcurrentHashMap<Int, Long>()
    var lastRefreshTime = 0L
    var lastAllDirtyRefreshAt = 0L
    var respFieldDiag = 0
    var respFieldCallDiag = 0
    var lastLoadMoreTime = 0L
    var adpListDumped = false
    var feedDiagCount = 0
    var lastFeedDiagSig = ""
    @Volatile var lastFeedDiagAt = 0L
    var nonVfDiagCount = 0
    var weakUnwrapDiag = 0
    var liveDiagCount = 0
    var movieDiagCount = 0
    var entFullDumpCount = 0
    var entScanDiag = 0
    var entFullProbeCount = 0
    var liveFieldDiag = 0
    var anyOnCache = false
    var anyOnAt = 0L
    val sigIdCache = java.util.concurrent.ConcurrentHashMap<Int, Boolean>()
    val feedFilterCache = java.util.Collections.synchronizedMap(java.util.WeakHashMap<Any, Boolean>())
    val contentFilterCache = java.util.Collections.synchronizedMap(java.util.WeakHashMap<Any, Boolean>())
    var fcacheDiag = 0
    val filterHitStats = java.util.concurrent.ConcurrentHashMap<String, Int>()
    var hitLogDiag = 0
    var quickDebugCount = 0
    var hitTotal = 0
    val feedSigCache = java.util.concurrent.ConcurrentHashMap<String, Boolean>()
    val contentSigCache = java.util.concurrent.ConcurrentHashMap<String, Boolean>()
    val asyncDecidePending = java.util.Collections.newSetFromMap(java.util.concurrent.ConcurrentHashMap<String, Boolean>())
}
